---
version: '3'
services:

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
      hostname: elasticsearch
      container_name: elasticsearch
      environment:
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
      - 9200:9200

  kibana:
      image: docker.elastic.co/kibana/kibana:7.9.0
      hostname: kibana
      container_name: kibana
      depends_on:
      - elasticsearch
      environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      ports:
      - 5601:5601
